workflows:
    sample-workflow:
        name: Android Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1
        environment:
            flutter: stable
            android_signing:
              - keystore_reference
        cache:
          cache_paths:
            - ~/.pub-cache
            - $HOME/.gradle/caches
        triggering:
          events:
            - push
        scripts:
            - name: Set up local.properties
              script: | 
                echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
            - name: Get Flutter packages
              script: | 
                flutter packages pub get
            - name: Flutter analyze
              script: | 
                flutter analyze
            - name: Build AAB with Flutter
              script: | 
                flutter build appbundle --release
            - name: Build universal APK
              script: | 
                android-app-bundle build-universal-apk
        artifacts:
            - build/**/outputs/**/*.aab
            - build/**/outputs/**/mapping.txt
            - flutter_drive.log
        publishing:
            email:
                recipients:
                - huy@nevercode.io
                notify:
                    success: true
                    failure: false